### ISSUE TITLE
Make nav responsive to window size

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/councildataproject.github.io#12]
The nav needs to be made responsive to small screen sizes.

See [here](https://protocol.mozilla.org/patterns/organisms/navigation.html) for how mozilla is injecting the mzp nav javascript

**Comment by hisa-shimoji** [comment]
I would like to work on this issue. I think [react-responsive package](https://www.npmjs.com/package/react-responsive) is effective.

**Comment by JacksonMaxfield** [comment]
Hey! Would be assume if you could take this on! Before you do so with the `react-responsive` package could you try to get it working with the mozilla protocol specific JS?

They have a js file they add the to document when they want navigation that works simply off of css class names and since we are already using their class names I assume it should work with minimal changes.

```html
<script
    src="../../../assets/protocol/protocol/js/protocol-menu.js">
</script>
```

See [here](https://protocol.mozilla.org/patterns/organisms/navigation.html) for more details.

If that doesn't seem to be working then feel free to use `react-responsive`.

**Comment by hisa-shimoji** [comment]
I checked the code in the mozilla’s JS file. Then I have created a pull request #22 with using react-responsive because I thought the way enable us to resolve this issue with smaller amount of code. If you agree that, please use the PR.
Only a code file, Navigation.js, is edited and mozzila css styles definition isn’t changed in the PR.
